
# os: osx

# osx_image: xcode11.2
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

cache: pip

services:
  - xvfb

python:
  - "3.9.1"

# command to install dependencies
install:
  - pip3 install click


# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
